entryPoints:
  web:
    address: ":80"
    # HTTP to HTTPS redirect
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  webhook:
    address: ":3333"

api:
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: dev@ivancavero.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
