# Traefik configuration for Ignis

# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false
  experimental:
    http3: true

# Log configuration
log:
  level: INFO
  format: common

# Access logs
accessLog:
  format: common

# API and dashboard configuration
api:
  dashboard: true
  insecure: false
  debug: false

# Entry points configuration
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  dashboard:
    address: ":8080"

# Providers configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Certificate resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      email: dev@ivancavero.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
